on: [push]

name: Docker PHP Demo with Login Form

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Docker
        run: |
          echo "Criando Dockerfile..."
          cat > Dockerfile << 'EOF'
          FROM php:apache
          COPY index.php /var/www/html/
          COPY login.php /var/www/html/
          EOF

      - name: Criar arquivos PHP
        run: |
          # index.php
          cat > index.php << 'EOF'
          <?php 
          session_start();
          if(isset($_SESSION['loggedin']) {
            echo '<h1>Bem-vindo ao Sistema!</h1>';
            echo '<a href="logout.php">Logout</a>';
          } else {
            header('Location: login.php');
          }
          ?>
          EOF

          # login.php
          cat > login.php << 'EOF'
          <?php
          session_start();
          $error = '';
          
          if($_SERVER['REQUEST_METHOD'] == 'POST') {
            $username = $_POST['username'];
            $password = $_POST['password'];
            
            // Credenciais do Conjur (serão injetadas como variáveis de ambiente)
            $valid_user = getenv('SQL_USERNAME');
            $valid_pass = getenv('SQL_PASSWORD');
            
            if($username === $valid_user && $password === $valid_pass) {
              $_SESSION['loggedin'] = true;
              header('Location: index.php');
            } else {
              $error = 'Credenciais inválidas!';
            }
          }
          ?>
          <!DOCTYPE html>
          <html>
          <head>
            <title>Login</title>
            <style>
              body { font-family: Arial, sans-serif; }
              .login-form { width: 300px; margin: 100px auto; }
              .error { color: red; }
            </style>
          </head>
          <body>
            <div class="login-form">
              <h2>Login</h2>
              <?php if($error): ?>
                <p class="error"><?php echo $error; ?></p>
              <?php endif; ?>
              <form method="POST">
                <div>
                  <label>Usuário:</label>
                  <input type="text" name="username" required>
                </div>
                <div>
                  <label>Senha:</label>
                  <input type="password" name="password" required>
                </div>
                <button type="submit">Entrar</button>
              </form>
            </div>
          </body>
          </html>
          EOF

          # logout.php
          echo '<?php session_start(); session_destroy(); header("Location: login.php"); ?>' > logout.php

      - name: Construir imagem Docker
        run: docker build -t php-demo .

      - name: Executar container Docker com variáveis de ambiente
        run: |
          docker run -d \
            -p 8081:80 \
            -e SQL_USERNAME=${{ secrets.SQL_USERNAME }} \
            -e SQL_PASSWORD=${{ secrets.SQL_PASSWORD }} \
            --name php-appteste \
            php-demoteste

  test:
    runs-on: self-hosted
    permissions:
      id-token: 'write'
      contents: 'read'
    steps:
      - name: Import Secrets using CyberArk Conjur Secret Fetcher Action
        uses: cyberark/conjur-action@v2.0.5
        with:
          url: ${{ secrets.CONJUR_URL }}
          account: cyberarkdemo
          authn_id: ${{ secrets.CONJUR_AUTHN_ID }}
          secrets: db/sqlusername|SQL_USERNAME;db/sql_password|SQL_PASSWORD
